sudo: false

language: ruby

rvm:
  - 2.3

cache: bundler
script: bash ./travis-deploy.sh

env:
  global:
    - GH_COMMIT_AUTHOR="Travis CI"
    - GH_COMMIT_EMAIL=travisci@cds-hooks.org
    - ENCRYPTION_LABEL=ddaacfe268bd

notifications:
  webhooks:
    - https://chat.fhir.org/api/v1/external/travis?stream=cds-hooks-committers&topic=ci-notifications&api_key=dX12ZMY66SWJDklEXwB8yMyvrGrlr8w0
